import { CosmeticItem, UpgradeItem } from '../types/economy';
import { WorldData } from '../types/progress';

export const ECONOMY_CONFIG = {
  CURRENCY_NAME: 'Shadow Shards',
  CURRENCY_SHORT: 'Shards',
  DISCLAIMER: 'Shadow Shards are strictly virtual in-game rewards with NO real-world value. Cannot be withdrawn or traded for cash.',

  // Reward Values
  REWARDS: {
    ENEMY_DEFEAT_GUARD: 15,
    ENEMY_DEFEAT_RAVEN: 20,
    ENEMY_DEFEAT_MONK: 25,
    ENEMY_DEFEAT_HUNTER: 35,
    ENEMY_DEFEAT_PHANTOM: 40,
    ENEMY_DEFEAT_SENTINEL: 50,
    BOSS_DEFEAT: 1000,

    SHARD_PICKUP: 5,
    MOON_SIGIL: 35,
    MEMORY_FRAGMENT: 50,
    HEALTH_PACK_HP: 35,

    LEVEL_CLEAR_BASE_SHARDS: 250,
    LEVEL_CLEAR_BASE_XP: 300,

    THREE_STAR_BONUS_SHARDS: 200,
    THREE_STAR_BONUS_XP: 250,

    PERFECT_NO_HIT_BONUS: 150,

    DAILY_MISSION_EASY: 200,
    DAILY_MISSION_MEDIUM: 350,
    DAILY_MISSION_HARD: 600,
  },

  // Level Progression Curve
  XP_PER_LEVEL_BASE: 500,
  XP_GROWTH_FACTOR: 1.18,
  MAX_PLAYER_LEVEL: 50,

  calculateXpForLevel(level: number): number {
    return Math.floor(this.XP_PER_LEVEL_BASE * Math.pow(this.XP_GROWTH_FACTOR, level - 1));
  },
};

export const INITIAL_UPGRADES: UpgradeItem[] = [
  {
    id: 'vitality',
    name: 'Shadow Vitality',
    description: 'Increases maximum life essence to endure deadlier strikes.',
    category: 'vitality',
    currentLevel: 1,
    maxLevel: 5,
    costs: [0, 300, 650, 1200, 2000],
    statLabel: 'Max Health',
    levelValues: ['100 HP', '125 HP', '150 HP', '175 HP', '200 HP'],
    icon: 'heart',
  },
  {
    id: 'blade',
    name: 'Void Blade Art',
    description: 'Hones katana sharpness, raising physical damage multiplier.',
    category: 'blade',
    currentLevel: 1,
    maxLevel: 5,
    costs: [0, 400, 850, 1500, 2500],
    statLabel: 'Blade Multiplier',
    levelValues: ['1.0x', '1.25x', '1.5x', '1.8x', '2.2x'],
    icon: 'flash',
  },
  {
    id: 'dash',
    name: 'Phantom Step',
    description: 'Refines shadow dash cooldown and burst distance.',
    category: 'dash',
    currentLevel: 1,
    maxLevel: 4,
    costs: [0, 500, 1000, 1800],
    statLabel: 'Dash Cooldown',
    levelValues: ['1.0s', '0.8s', '0.65s', '0.5s'],
    icon: 'speedometer',
  },
  {
    id: 'double_jump',
    name: 'Moonlight Somersault',
    description: 'Unlocks mid-air double jump for effortless acrobatic evasion.',
    category: 'double_jump',
    currentLevel: 0,
    maxLevel: 1,
    costs: [600],
    statLabel: 'Air Jump',
    levelValues: ['Locked', 'Unlocked'],
    icon: 'arrow-up-circle',
  },
  {
    id: 'special',
    name: 'Nightfall Tempest',
    description: 'Empowers special shadow wave shuriken damage and radius.',
    category: 'special',
    currentLevel: 1,
    maxLevel: 4,
    costs: [0, 450, 950, 1750],
    statLabel: 'Special Strike',
    levelValues: ['40 DMG', '65 DMG', '95 DMG', '140 DMG'],
    icon: 'disc',
  },
];

export const INITIAL_COSMETICS: CosmeticItem[] = [
  {
    id: 'skin_default',
    name: 'Shadow Initiate',
    type: 'skin',
    description: 'The standard dark woven cowl worn by Moonlit Veil acolytes.',
    cost: 0,
    rarity: 'Common',
    color: '#1a1f2c',
    accentColor: '#48cae4',
    unlocked: true,
    equipped: true,
  },
  {
    id: 'skin_crimson',
    name: 'Crimson Ronin',
    type: 'skin',
    description: 'Scarlet lacquered plates forged from molten obsidian embers.',
    cost: 800,
    rarity: 'Rare',
    color: '#800e13',
    accentColor: '#ff4d6d',
    unlocked: false,
    equipped: false,
  },
  {
    id: 'skin_wraith',
    name: 'Moonlight Wraith',
    type: 'skin',
    description: 'Ghostly pale silks that refract starlight into blinding mist.',
    cost: 1500,
    rarity: 'Epic',
    color: '#0d2838',
    accentColor: '#00f5d4',
    unlocked: false,
    equipped: false,
  },
  {
    id: 'skin_golden',
    name: 'Golden Shinobi',
    type: 'skin',
    description: 'Ceremonial gilded regalia blessed by the Sunken Temple priests.',
    cost: 3000,
    rarity: 'Legendary',
    color: '#38220f',
    accentColor: '#ffd166',
    unlocked: false,
    equipped: false,
  },
  {
    id: 'trail_smoke',
    name: 'Abyssal Fog',
    type: 'trail',
    description: 'A lingering vortex of charcoal smoke on dash.',
    cost: 0,
    rarity: 'Common',
    color: '#343a40',
    accentColor: '#6c757d',
    unlocked: true,
    equipped: true,
  },
  {
    id: 'trail_sakura',
    name: 'Blood Sakura',
    type: 'trail',
    description: 'Ethereal crimson blossoms scatter behind your blades.',
    cost: 700,
    rarity: 'Rare',
    color: '#ff4d6d',
    accentColor: '#ff758f',
    unlocked: false,
    equipped: false,
  },
  {
    id: 'trail_lightning',
    name: 'Cyan Arc',
    type: 'trail',
    description: 'Crackling moonlight sparks whenever you burst into motion.',
    cost: 1400,
    rarity: 'Epic',
    color: '#48cae4',
    accentColor: '#90e0ef',
    unlocked: false,
    equipped: false,
  },
];

export const ALL_WORLDS: WorldData[] = [
  {
    id: 1,
    name: 'Moonlit Forest',
    tagline: 'Silent Canopies & Whispering Pines',
    description: 'The sacred woodland guarding the eastern shrine. Shadow Guards patrol the moss-covered rocks while Raven Scouts scour the skies.',
    themeColor: '#0f2427',
    accentColor: '#48cae4',
    unlocked: true,
    requiredStars: 0,
    levelsCount: 5,
    bossName: 'Kage-no-Oni (The Revenant)',
    bossDefeated: false,
  },
  {
    id: 2,
    name: 'Forgotten Temple',
    tagline: 'Sunken Sanctuaries & Ancient Relics',
    description: 'Ruins of a sunken monastic order. Corrupted Temple Monks cast homing spirit orbs across collapsing stone corridors.',
    themeColor: '#2b1e13',
    accentColor: '#fca311',
    unlocked: false,
    requiredStars: 10,
    levelsCount: 5,
    bossName: 'High Monk Gendo',
    bossDefeated: false,
  },
  {
    id: 3,
    name: 'Shadow Canyon',
    tagline: 'Abyssal Winds & Shifting Crags',
    description: 'Vertical precipices where bottomless depths swallow the unwary. Teleporting Phantoms strike from thin air.',
    themeColor: '#1c142b',
    accentColor: '#b5179e',
    unlocked: false,
    requiredStars: 22,
    levelsCount: 5,
    bossName: 'The Abyssal Wraith',
    bossDefeated: false,
  },
  {
    id: 4,
    name: 'Iron Fortress',
    tagline: 'Gears of War & Steam Hazards',
    description: 'A colossal mechanical citadel bristling with iron crushers, flamethrower vents, and heavily armored Iron Hunters.',
    themeColor: '#25211e',
    accentColor: '#e63946',
    unlocked: false,
    requiredStars: 35,
    levelsCount: 5,
    bossName: 'Goliath Sentinel IV',
    bossDefeated: false,
  },
  {
    id: 5,
    name: 'Nightfall Castle',
    tagline: 'Throne of The Hollow',
    description: 'The epic epicenter of darkness. Only a master ninja wielding fully awakened shadow arts can pierce its core.',
    themeColor: '#120719',
    accentColor: '#ff0054',
    unlocked: false,
    requiredStars: 48,
    levelsCount: 5,
    bossName: 'Lord of The Hollow',
    bossDefeated: false,
  },
];
