export const PHYSICS = {
  GRAVITY: 980,
  MOVE_SPEED: 260,
  ACCELERATION: 1500,
  DECELERATION: 1600,
  JUMP_FORCE: -440,
  DOUBLE_JUMP_FORCE: -390,
  WALL_SLIDE_SPEED: 95,
  WALL_JUMP_IMPULSE_X: 290,
  WALL_JUMP_IMPULSE_Y: -410,
  DASH_SPEED: 650,
  DASH_DURATION: 0.2, // seconds
  DASH_COOLDOWN: 1.0, // seconds
  COYOTE_TIME: 0.12, // grace period after stepping off edge
  JUMP_BUFFER_TIME: 0.12, // grace period for jump press before landing
  INVULNERABLE_DURATION: 1.2,
  ATTACK_DURATION: 0.22,
  ATTACK_COOLDOWN: 0.15,
  ATTACK_RANGE: 55,
  SPECIAL_COST: 40,
  SPECIAL_SPEED: 520,
  SPECIAL_LIFETIME: 1.4,
  MAX_FALL_SPEED: 700,
  FRICTION: 0.82,
};
